### ISSUE TITLE
"Add a paper" and "Settings" buttons not working on local

### ISSUE THREAD

**Issue by Uncoolagain** [DejaLus/DjLu#2]
Hi!
After running the script 'run_test_server.sh' and register a new user, the buttons "Add a paper" and "Settings" don't show anything. However, the "Logout" button works.
I tested it on Safari and Firefox.

**Comment by ThomasRobertFr** [comment]
Hi,
That's strange. Could you open a web console (https://developer.mozilla.org/en/docs/Tools/Web_Console) and tell us if any error is shown there at the loading of the page of when you click on the buttons?

Both those buttons are supposed to display a sort of popup (like the one for login for example) using JS.

**Comment by MicaelCarvalho** [comment]
In the current version of DjLu, the admin is supposed to configure a file googleAPI.json at the root of the system in order to provide integration with the Google Drive API. Right now we're working on making it optional (https://trello.com/c/JtO7lbhd), so we should have a fix soon.
