### ISSUE TITLE
Pinning left nav bar mask read status

### ISSUE THREAD

**Issue by edouardelasalles** [DejaLus/DjLu#3]
When the left bar in pinned, the read status tags are masked

**Comment by ThomasRobertFr** [comment]
Yep, introduced with the feature https://github.com/DejaLus/DjLu/commit/603f414833962ef90b47ed07d648575c8d9f3d4b, needs a bit of additional CSS to fix this up.

**Comment by ThomasRobertFr** [comment]
Add `#papers-table { position: relative; }` poke @MicaelCarvalho
