### ISSUE TITLE
Self-hosting instructions

### ISSUE THREAD

**Issue by nshaud** [DejaLus/DjLu#4]
Hi,

This seems like a very interesting project! Do you have any setup instructions to self-host this? By the way, is the project still active?

Cheers!

**Comment by MicaelCarvalho** [comment]
Hello @nshaud,

Thank you. The project is still alive, but as we only implement new features on our free time, and there hasn't been much lately, it progresses slowly. Feel free to contribute if you feel like it, we also have a Trello with everything that we plan to do: https://trello.com/b/6xvhb31I/djlu

To setup a DjLu server, you have to install PHP 5.6 and its XML extension: `sudo apt-get install php5.6 php5.6-xml` in debian-like or apt-get capable systems, then put the project inside your www/public_html folder.

If you want to enable Google Drive, you have to put the drive's `googleAPI.json` file in the root directory of the project (same place as the `index.php`). You can get it here: https://console.developers.google.com/start/api?id=drive

As for Git, for now each user must manually receive the authorization from the sysadmin. Users' registrations are kept inside the file `users.json`, that is created inside the folder `data` once the system is up and the first user is registered. To enable Git you have to add "git" inside the `rights` list of that user.

Hope this helps, please let me know if you find any problems during the installation/setup. :)

**Comment by nshaud** [comment]
Okay. FYI, the APC cache is deprecated in PHP 7. I managed to get DjLu to load using the APCu_bc backward compatibility extension. However it does not load any page except the index (returns a 404). I've got nothing in the Apache logs so it's a bit weird.

Using the `run_test_server.sh` script, I managed to register but login returns:
```
[lib/base.php:2032] Base->error(500,'count(): Parameter must be an array or an object that implements Countable')
[app/models/user.php:244] count(DBJigMapper::__set_state(array()))
[app/pages/login.php:23] models\User->login('test','$2a$12$y0fK0u1hE3Nr2F9Wwdq8lOwjNEicKYJcr4zSfbljxj4TT17coFUKW')
```

**edit :** well, this seems like a PHP 7 issue. I'll try to build a Docker or something using PHP 5.6.

**edit2 :** it works using Docker and a PHP 5.6 image.

**Comment by ozansener** [comment]
@nshaud Can you post the configuration of the Docker image? I still can not make it work

Update: I made it work in AWS with Linux AMI, php5.6 and adding a special .htaccess file. I think a proper .htaccess file should be added to the repo

**Comment by nshaud** [comment]
@ozansener I used this as a Dockerfile:
```
FROM php:5.6
WORKDIR .
ADD . /app/
EXPOSE 8080
CMD ["sh", "./app/run_test_server.sh"]
```

This work quite well for testing.

**Comment by MicaelCarvalho** [comment]
651efb8aba6f5b05d5db00a79a43b6ba494b873e solved this issue. Of course better installation instructions would be useful for the README. Contributions are welcome. ;)

**Comment by sebdumancic** [comment]
Could you provide more details about settings the connection with Drive?
I'm having a bit of a trouble making it work.

Error:

Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://0.0.0.0:8080/api/drive/auth

Request Details
  response_type=code
  redirect_uri=http://0.0.0.0:8080/api/drive/auth
  client_id=[...].apps.googleusercontent.com
  scope=https://www.googleapis.com/auth/drive
  access_type=offline
  approval_prompt=auto
