### ISSUE TITLE
Sync Library in Google Drive

### ISSUE THREAD

**Issue by nikonikolov** [DejaLus/DjLu#7]
Is there existing way to sync my current library to Google Drive instead of a git repo. I think this will be easier since it will remove the requirement to constantly pull/commit/push.

In the meantime, how can I get git enabled for my account? Thanks!

**Comment by MicaelCarvalho** [comment]
Hello,

When you add a paper to DjLu, you can select it, and click the button in the middle after the URL (Upload PDF to Google Drive from URL). The website will prompt you to authenticate to Google Drive. We are currently working on a more intuitive way of connecting Google Drive accounts.

As for the git access, I'm getting the required permissions (we had a recent change in privileges), and I will get back as soon as possible. :-)

Micael

**Comment by MicaelCarvalho** [comment]
Your user has now git access. Closing this issue, please ping me back if there is any issue. ;)
