### ISSUE TITLE
Pushing my library to the Git or my own server

### ISSUE THREAD

**Issue by ozansener** [DejaLus/DjLu#8]
Grat project and I just started to use it. I was wondering can I get an access for git? If not, I will put it in my own server; but, I still need some way to extract my library.

**Comment by MicaelCarvalho** [comment]
Hello,

I'm getting the required permissions (we had a recent change in privileges), and I will get back as soon as possible. :-)

Micael

**Comment by MicaelCarvalho** [comment]
Your user has now git access. Closing this issue, please ping me back if there is any issue. ;)
