### ISSUE TITLE
Website should use https

### ISSUE THREAD

**Issue by joe-antognini** [DejaLus/DjLu#9]
It looks like when registering passwords are currently sent in plaintext.  The website should use https to prevent that.

**Comment by MicaelCarvalho** [comment]
It is true we should use https for the demo server, also provide easier ways to set up DjLu in a secure environment. However, after registration, it should be secure to use, even without HTTPS. But djlu.fr is meant to be a demo, not a final product — unfortunately we don't have the structure to host a full-fledged server. I'll leave this Issue open and add a task to our TO-DO list to verify this. Thank you :)

**Comment by MicaelCarvalho** [comment]
For now, marking this as won't fix, because it does not seem to be critical for the advancement of the project. Anyone is free to set up DjLu in a secure manner should they choose install it on their servers, of course. :)
